server:
  port: 8088
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/service/user/**

        - id: reclamation-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/services/reclamation/**

        - id: reponse-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/services/reponse/**


      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200" # Allow requests from Angular app
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600 # Cache preflight response for 1 hour
