server:
  port: 8088

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/service/user/**

        - id: reclamation-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/services/reclamation/**

        - id: reponse-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/services/reponse/**

        - id: shop-service
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/articles/**

        - id: order-service
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/orders/**
        - id: basket-service
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/basket/**
        - id: order-service
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/reports/**



      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
